#ifndef CAPTURE_SCENARIO_H_
#define CAPTURE_SCENARIO_H_

#include <stdint.h>
#include "nrf51_bitfields.h"	/* Used for the specific power values */

#define SCENARIO 0
#define COUNT 1
#define SENDER 2
#define DELAY 3
#define MULT 4
#define	POWERA 5
#define POWERB 6
#define OPTIONAL 7

#define SCENARIO_NUMBER 4

/* FORMAT:
 *
 * Scenario, Count, Sender, Delay, Multiplier, PowerA, PowerB, Sequence
 *
 */

uint8_t scenario[SCENARIO_NUMBER][8] =
	{
	    {0, 0, 8, 0, 0, RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg12dBm, 0},

	    {1, 0, 8, 98, 16, RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg4dBm, 0},

	    {2, 0, 8, 8, 16,  RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg8dBm, 0},

	    {3, 0, 8, 8, 16, RADIO_TXPOWER_TXPOWER_0dBm, RADIO_TXPOWER_TXPOWER_Pos4dBm, 0},
	};





/*		EARLY TESTS (see capture-tests spreadsheet)
 *
 *	    {0, 0, 8, 0, 0, RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg16dBm, 0},

	    {1, 0, 8, 250, 1, RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg16dBm, 0},

	    {2, 0, 8, 250, 1,  RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg20dBm, 0},

	    {3, 0, 8, 120, 1, RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg20dBm, 0},

	    {4, 0, 8, 64, 1, RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg16dBm, 0},

	    {5, 0, 8, 64, 1, RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg20dBm, 0},

	    {6, 0, 8, 64, 1, RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg30dBm, 0},
 *
 */

/*		Capture tests
 *
 * 	    {0, 0, 8, 0, 0, RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg12dBm, 0},

	    {1, 0, 8, 250, 100, RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg12dBm, 0},

	    {2, 0, 8, 65, 10,  RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg4dBm, 0},

	    {3, 0, 8, 24, 16, RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg12dBm, 0},

	    {4, 0, 8, 150, 1, RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg12dBm, 0},

	    {5, 0, 8, 128, 1, RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg12dBm, 0},

	    {6, 0, 8, 120, 1, RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg12dBm, 0},

	    {7, 0, 8, 64, 1, RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg12dBm, 0},

	    {8, 0, 8, 56, 16, RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg12dBm, 0},

	    {9, 0, 8, 48, 16, RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg4dBm, 0},

	    {10, 0, 8, 65, 10, RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg4dBm, 0},

	    {11, 0, 8, 128, 1, RADIO_TXPOWER_TXPOWER_Pos4dBm, RADIO_TXPOWER_TXPOWER_Neg4dBm, 0},
*/


#endif /*CAPTURE_SCENARIO_H_ */
